version: '3.7'

services:
    db:
        image: mongo:latest
        volumes:
            - "db-data:/data/db"
        networks:
            - "simple-jwt-api-mongo"

    app:
        image: image:latest
        volumes:
            - "app-data:/app/storage"
        networks:
            - "simple-jwt-api-mongo"
        environment:
            NODE_ENV: production
            PORT: 8080
            APP_KEY: 1234
            DB_URI: mongodb://db:27017
            DB_NAME: simple_jwt_api
        ports:
            - "8080:8080"

volumes:
  db-data:
  app-data:

networks:
  simple-jwt-api-mongo: